classrooms/block/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views

router = routers.DefaultRouter()
router.register(r'chains', views.ChainViewSet)

urlpatterns = [
	url('', include(router.urls)),
    url(r'^blocks/(?P<chain_name>[A-Za-z0-9-]+)/latest$', views.LatestBlockApiView.as_view(), name='latest-block'),
    url(r'^blocks/(?P<chain_name>[A-Za-z0-9-]+)/mine-block$', views.BlockCreateView.as_view(), name='mine-block'),
    url(r'^blocks/(?P<hash>[A-Za-z0-9-]+)$', views.BlockApiView.as_view(), name='get'),
    url(r'^chains/(?P<name>[A-Za-z0-9-]+)$', views.ChainApiView.as_view(), name='chain'),
    url(r'^peers/$', views.PeerApiView.as_view(), name='peers'),
    url(r'^peers/add$', views.PeerApiView.as_view(), name='add-peer'),
    url(r'^transaction/$', views.TransactionsList.as_view(), name='transaction'),
]

classrooms/classrooms/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from classrooms import settings
from school.views import seeallschoolsbyquery
from django.views.static import serve 

urlpatterns = [
    path('datawizard/', include('data_wizard.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin_url/', admin.site.urls),
    url(r'^$', seeallschoolsbyquery),
    url('chain/', include('block.urls')),
    url('contracts/', include('contract.urls')),
    url('schools/', include('school.urls')),
    url('users/', include('school_users.urls')),
]
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

handler404 = 'school_users.views.handler404'
handler500 = 'school_users.views.handler500'

classrooms/contract/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views
from classrooms import settings

router = routers.DefaultRouter()
router.register(r'contracts', views.ContractsViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'contracts'
urlpatterns = [
    url('', include(router.urls)),
    path('mark_slm_purchased/<int:contract_id>', views.mark_slm_purchased, name="mark_slm_purchased"),
    url('createacontract/', views.createacontract, name="createacontract"),
    url('createacontract_rest/', views.createacontract_rest, name="createacontract_rest"),
    path('seecontractdetails/<int:contract_id>', views.seecontractdetails, name="seecontractdetails"),
    path('select_director_to_contract/<int:contract_id>', views.select_director_to_contract, name="select_director_to_contract"),
    url('all/', views.seecontractsbyquery, name="seemycontracts"),
    url('all_rest/', views.seemycontracts_rest, name="seemycontracts_rest"),
    path('set_signed/<int:contract_id>', views.set_signed, name='set_signed'),
    path('queue_set_signed/<int:contract_id>', views.queue_set_signed, name='queue_set_signed'),
    path('set_signed_rest/<int:contract_id>', views.set_signed_rest, name='set_signed_rest'),
    path('updatecontract/<int:contract_id>', views.updatecontract, name='updatecontract'),
    path('delete_contract/<int:contract_id>', views.delete_contract, name='delete_contract'),
    path('redirect_to_slm_link/<int:contract_id>', views.redirect_to_slm_link, name='redirect_to_slm_link'),
    path('seefinancialdetails/', views.seefinancialdetails, name='seefinancialdetails'),
    url('select_student_to_contract/', views.select_student_to_contract, name='select_student_to_contract'),
    path('select_student_to_contract_update/<int:contract_id>', views.select_student_to_contract_update, name='select_student_to_contract_update'),
    path(r'serve_protected/{}<path>/<int:contract_id>/<type_of_document>'.format(settings.MEDIA_URL[1:]), views.protected_serve, {'document_root': settings.MEDIA_ROOT}, name='serve_protected'),
    path('set_contract_paid/<int:contract_id>', views.set_contract_paid, name='set_contract_paid'),
    path('directors/ajax', views.directors_choices_ajax, name='directors_choices_ajax'),
    path('receive_maple_result/', views.receive_maple_result, name='receive_maple_result'),
    path('authenticated/', views.authenticated_google, name='authenticated'),
    path('upload_contract_file_to_drive/<int:contract_id>/<type_of_file>', views.upload_contract_file_to_drive, name='upload_contract_file_to_drive'),
    path('extend_expire_date/<int:contract_id>', views.extend_expire_date, name='extend_expire_date'),
    path('edit_dates/<int:contract_id>', views.edit_dates, name='edit_dates'),
]

classrooms/school_users/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from django.contrib.auth.views import PasswordResetView

# router = routers.DefaultRouter()
# router.register(r'schools', views.SchoolsViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'users'
urlpatterns = [
    # url('', include(router.urls)),
    url('create_user/', views.create_user, name="create_user"),
    url('all_administration/', views.seeusersbyquery_administration, name="all_administration"),
    url('all_signes/', views.seeusersbyquery_signes, name="all_signes"),
    path('all_by_school/<int:school_id>', views.seeallusers_by_school, name='seeallusers_by_school'),
    url('all_rest/', views.seeallusers_rest),
    path('delete_user/<int:user_id>/<type_of_user>', views.delete_user, name='delete_user'),
    path('set_parents/<int:student_id>/', views.set_parents, name='set_parents'),
    path('add_parent/<int:student_id>/<type_of_user>', views.add_parent, name='add_parent'),
    path('select_parent/<int:student_id>/<type_of_user>', views.select_parent, name='select_parent'),
    path('confirm_parent/<int:student_id>/<int:parent_id>/<type_of_user>', views.confirm_parent, name='confirm_parent'),
    path('add_first_parent/<int:student_id>', views.add_first_parent, name='add_first_parent'),
    path('add_second_parent/<int:student_id>', views.add_second_parent, name='add_second_parent'),
    path('classes/ajax', views.classes_choices_ajax, name='classes_choices_ajax'),
    path('students/ajax', views.students_choices_ajax, name='students_choices_ajax'),
    url('add_student/', views.add_student, name='add_student'),
    url('login/', views.do_login, name='login'),
    path('login_from_other_system/<username>', views.login_from_other_system, name='login_from_other_system'),
    url('logout', views.do_logout, name='logout'),
    url('api/login', obtain_jwt_token, name='login_rest'),
    url('api/refresh_token', refresh_jwt_token, name='refresh_token'),
    url('current_user/', views.current_user, name='current_user'),
    path('create_head_to_school/<int:school_id>', views.create_head_to_school, name='create_head_to_school'),
    path('create_supervisor_to_school/<int:school_id>', views.create_supervisor_to_school, name='create_supervisor_to_school'),
    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.reset_password, name='reset_password'),
    url('generate_password', views.generate_password, name='generate_password'),
    url('profile', views.profile, name='profile'),
    url('update_perfil', views.update_profile, name='update_perfil'),
    path('do_u_need_parents/<int:student_id>/<int:school_id>/<int:class_id>', views.do_u_need_parents, name='do_u_need_parents'),
    path('seesonsofparent/<int:parent_id>', views.seesonsofparent, name='seesonsofparent'),
    path('reset_password_send_email/<int:user_id>/<type_of_user>', views.reset_password_send_email, name='reset_password_send_email'),
    path('change_email/<user_id>', views.change_email, name='change_email'),
    path('room/<str:room_name>/', views.room, name='room'),
    url('forgot_password', views.forgot_password, name='forgot_password'),
]

classrooms/contract/models.py
from django.db import models
from school_users.models import *
from datetime import datetime    

# Create your models here.
class Contract(models.Model):
    """docstring for Contract"""
    # Data from Sponte #
    contract_id_sponte = models.IntegerField(null=True, blank=True)
    contract_free_class_id_sponte = models.IntegerField(null=True, blank=True, verbose_name = 'Id do Contrato de Aula Livre Sponte')
    situation_id_sponte = models.IntegerField(null=True, blank=True, verbose_name = 'Id da Situação Sponte')
    situation_sponte = models.TextField(null=True, blank=True, verbose_name = 'Situação Sponte')
    student_name_sponte = models.TextField(null=True, blank=True, verbose_name = 'Nome do Estudante Sponte')
    student_id_sponte = models.IntegerField(null=True, blank=True, verbose_name = 'Id do Estudante Sponte')
    course_id_sponte = models.TextField(null=True, blank=True, verbose_name = 'Id do Curso Sponte')
    class_id_sponte = models.IntegerField(null=True, blank=True, verbose_name = 'Id da Aula Sponte')
    class_name_sponte = models.TextField(null=True, blank=True, verbose_name = 'Nome da Aula Sponte')
    course_name_sponte = models.TextField(null=True, blank=True, verbose_name = 'Nome do Curso Sponte')
    contract_type_id = models.IntegerField(null=True, blank=True, verbose_name = 'Id do Tipo de Contrato Sponte')
    initial_date_sponte = models.TextField(null=True, blank=True, verbose_name = 'Data Inicial do Contrato Sponte')
    end_date_sponte = models.TextField(null=True, blank=True, verbose_name = 'Data Final do Contrato Sponte')
    date_of_registration_sponte = models.TextField(null=True, blank=True, verbose_name = 'Data de Registro Sponte')
    type_of_registration_sponte = models.IntegerField(null=True, blank=True, verbose_name = 'Tipo de Registro Sponte')
    contractor_sponte = models.TextField(null=True, blank=True, verbose_name = 'Contratante Sponte')
    name_of_curricular_matrix_sponte = models.TextField(null=True, blank=True, verbose_name = 'Nome da Matriz Curricular Sponte')
    financial_launched_sponte = models.TextField(null=True, blank=True, verbose_name = 'Financeiro Lançado Sponte')
    contract_number_sponte = models.TextField(null=True, blank=True, verbose_name = 'Número do Contrato Sponte')
    closing_date_sponte = models.TextField(null=True, blank=True, verbose_name = 'Data de Fechamento Sponte')
    # end of Data from Sponte #
    # Basic data of the contract #
    contract_id = models.AutoField(primary_key=True)
    name = models.TextField(null=True, blank=True, verbose_name = 'Nome do Contrato')
    date = models.DateField(null=True, blank=True, verbose_name = 'Data Inicial do Contrato')
    end = models.DateField(null=True, blank=True, default="2020-12-31",verbose_name = 'Data Final do Contrato')
    expiration = models.DateField(null=True, blank=True, default="2020-12-31",verbose_name = 'Data de Expiração de Assinatura do Contrato')
    first_auth_signed = models.BooleanField(default=False)
    second_auth_signed = models.BooleanField(default=False)
    third_auth_signed = models.BooleanField(default=False)
    first_witness_signed = models.BooleanField(default=False)
    second_witness_signed = models.BooleanField(default=False)
    student_auth_signed = models.BooleanField(default=False)
    counter_signed = models.BooleanField(default=False)
    all_witness_signed = models.BooleanField(default=False)
    all_signed = models.BooleanField(default=False)
    pdf = models.FileField(null=True, blank=True, verbose_name = 'Contrato (PDF apenas e tamanho máximo de 2MB)')
    terms_of_contract = models.FileField(null=True, blank=True, verbose_name = 'Termos Aditivos do Contrato (1) (PDF apenas e tamanho máximo de 2MB)')
    terms_of_contract_2 = models.FileField(null=True, blank=True, verbose_name = 'Termos Aditivos do Contrato (2) (PDF apenas e tamanho máximo de 2MB)')
    first_auth_signe = models.ForeignKey(Parent, on_delete=models.SET_NULL, null=True, blank=True, related_name='first_responsible', default=None)
    second_auth_signe = models.ForeignKey(Parent, on_delete=models.SET_NULL, null=True, blank=True, related_name='second_responsible', default=None)
    third_auth_signe = models.ForeignKey(Parent, on_delete=models.SET_NULL, null=True, blank=True, related_name='third_responsible', default=None)
    first_witness_signe = models.ForeignKey(Witness, on_delete=models.SET_NULL, null=True, blank=True, related_name='first_witness', default=None)
    second_witness_signe = models.ForeignKey(Witness, on_delete=models.SET_NULL, null=True, blank=True, related_name='second_witness', default=None)
    student_auth_signe = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True, blank=True, related_name='student_responsible', default=None)
    counter_signe = models.ForeignKey(Head, on_delete=models.SET_NULL, null=True, blank=True, related_name='financial_responsible', default=None)
    first_auth_signed_timestamp = models.DateTimeField(null=True, blank=True)
    second_auth_signed_timestamp = models.DateTimeField(null=True, blank=True)
    third_auth_signed_timestamp = models.DateTimeField(null=True, blank=True)
    student_auth_signed_timestamp = models.DateTimeField(null=True, blank=True)
    first_witness_signed_timestamp = models.DateTimeField(null=True, blank=True)
    second_witness_signed_timestamp = models.DateTimeField(null=True, blank=True)
    counter_signed_timestamp = models.DateTimeField(null=True, blank=True)
    first_auth_hash = models.CharField(max_length=255, null=True, blank=True)
    second_auth_hash = models.CharField(max_length=255, null=True, blank=True)
    third_auth_hash = models.CharField(max_length=255, null=True, blank=True)
    first_witness_hash = models.CharField(max_length=255, null=True, blank=True)
    second_witness_hash = models.CharField(max_length=255, null=True, blank=True)
    student_auth_hash = models.CharField(max_length=255, null=True, blank=True)
    counter_auth_hash = models.CharField(max_length=255, null=True, blank=True)
    slm = models.TextField(null=True, blank=True)
    chain = models.ForeignKey('block.Chain', on_delete=models.SET_NULL, null=True, blank=True, verbose_name = 'Cadeia da Turma')
    email_sent = models.BooleanField(default=False)
    sent_date = models.DateTimeField(blank=True, null=True)
    student_name = models.TextField(null=True, blank=True)
    student_id = models.IntegerField(null=True, blank=True)
    purchased_slm = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_paid = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_expired = models.BooleanField(default=False)
    is_sent_to_drive = models.BooleanField(default=False)
    
    # end of Basic data of the contract #

            

classrooms/contract/templates/contract/authenticated.html
{% extends 'base.html'%}

{% block title %} Você está autenticado com o google {% endblock %}

{% block content %}

{% load static %}
<script>
    $(document).ready(function () {
        $('.container').removeClass('container');
    });
</script>

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <div class="card w-50">
                    <div class="card-header">
                        <h4 class="card-title" align="left">
                            {% if authorization_url %}
                                Clique no botão abaixo para se autorizar com Google
                            {% else %}
                                Você está autenticado com o google
                            {% endif %}
                        </h4>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div style="margin-top: 10px; margin-left: 10px; margin-bottom: 10px;">
                                {% if authorization_url %}
                                    <a href="{{ authorization_url }}" class="btn btn-primary">
                                        Autorizar com Google
                                    </a>
                                {% else %}
                                    <a href="{% url 'contracts:seemycontracts' %}" class="btn btn-success">
                                        Voltar Para Contratos
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
</div>
</div>
<script>(function (e, t, n) { var r = e.querySelectorAll("html")[0]; r.className = r.className.replace(/(^|\s)no-js(\s|$)/, "$1js$2") })(document, window, 0);</script>

{% endblock %}

classrooms/contract/templates/contract/contracttorender.html
{% autoescape off %}
<div id="pdf-id" style="overflow: hidden auto; margin: 0px auto; padding: 5px;">
	Name of the signe: {{ user.name }}
	Hash of the signe: {{ block.hash }}
</div>
{% endautoescape %}

classrooms/contract/templates/contract/createacontract.html
{% extends 'base.html'%}

{% block title %} Criar um Novo Contrato Para o Aluno {{ student.name }} {% endblock %}

{% block content %}

{% load static %}
<script>
	$(document).ready(function () {
		$('.container').removeClass('container');
	});
</script>

<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-9">
				<div class="card w-50">
					<div class="card-header">
						<h4 class="card-title" align="left">{% if student %}Criar um Novo Contrato Para o Aluno {{ student.name }}{% elif students %}Criar um Novo Contrato Para Múltiplos Alunos{% endif %}</h4>
					</div>
					<div class="card-body">
						<div class="row">
							<div class="col-md-11 pr-1">
								<div class="form-group">
									<form method="POST" class="" enctype="multipart/form-data" id="myForm"
									data-urlclasses="{% url 'contracts:directors_choices_ajax' %}"> {% csrf_token %}
										<div style="margin-top: 10px">
											<p><label>Por favor não enviar arquivos com os seguintes caracteres no nome: ã, á, à, é, è, í, ì, õ, ó, ò, ú, ù, ç. Isso também inclui estes mesmos caracteres em minúsculo.</label><br>
											</div>
											<input type="hidden" id="selected_user" name="selected_user" value="0">
											{{ form.as_p }}
											<div class="labelandform">
												<p><label>Selecione o diretor:</label></p>
												<select class="custom-select" id="select_form_class">
													<option id="" value="" selected></option>
												</select>
											</div>
											<div style="margin-top: 10px">
												<p><label>Você deseja enviar este contrato por email? (Recomendado)</label><br><label
													style="margin-right: 10px">Não</label><label class="switch">
														<input type="checkbox" id="first_checkbox" checked>
														<a id="first_slider" class="slider round"></a>
													</label><label style="margin-left: 10px">Sim</label></p>
												</div>
												<div>
													<p><label>Você deseja agendar o envio deste email?</label><br><label
														style="margin-right: 10px">Não</label><label class="switch"><input
															type="checkbox" id="second_checkbox"><a id="second_slider"
															class="slider round" onclick="select()"></a></label><label
															style="margin-left: 10px">Sim</label></p><input type="hidden"
															id="wish_today" name="wish_today" value="sim">
														</div>
														<div id="pai">
														</div>
														<div id="child">
														</div>
														<input type="hidden" id="wish" name="wish" value="sim">


														<div><button type="submit" class="btn btn-info btn-fill btn-sm pull-left mt-2"
															style="background-color: #213f99; border-color: #213f99">Criar Novo
														Contrato</button></div>

													</form>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>
				<script type="text/javascript">
					$(document).ready(function () {
						$('#id_chain').on('change', function () {
							setGenPasswordToFields(['id_{{user_form.password1.name}}', 'id_{{user_form.password2.name}}']);
							let urlClasses = $('#myForm').data('urlclasses')
							var selectValor = $(this).val();
							$.ajax({
								url: urlClasses,
								data: {
									id: selectValor
								},
								success: function (response) {
									$('#select_form_class').html(response)
								}
							})
						});
					});
					$(document).ready(function () {
						$('#select_form_class').on('change', function () {
							var selectValor = $(this).val();
							if (selectValor == '') {
								document.getElementById('selected_user').value = '0'
							}
							else {
								document.getElementById('selected_user').value = selectValor
							}
						});
					});
					$(document).ready(function () {
						$('#first_input').on('change', function () {
							var selectValor = $(this).val($(this).is(':checked'));
							if (selectValor == '') {
								$('#pai').children('div').remove();
								$('#child').children('div').remove();
							}
							else if (selectValor == true) {

							}
							else if (selectValor == false) {
								$('#pai').children('div').remove();
								$('#child').children('div').remove();
								document.getElementById('wish').value = 'não'
								document.getElementById('wish_today').value = 'não'
							}
						});
					});
					$(document).on("click", "#first_slider", function () {
						if (!$('#first_checkbox').prop("checked")) {
							document.getElementById('wish').value = 'sim'
							$('#first_checkbox').attr('checked')
						}
						else {
							$('#pai').children('div').remove();
							$('#child').children('div').remove();
							document.getElementById('wish').value = 'não'
							$('#first_checkbox').removeAttr('checked')
						}
					});
					function select() {
						if (!$('#second_checkbox').prop("checked")) {
							$('#child').append('<div id="não"><p><div class="form-group"><label>Que dia você deseja que seja enviado o seu contrato?</label><label>Data do Agendamento: </label><input class="form-control" type="date" name="date" min="{{ tomorrow }}"></div><div class="form-group"><label>Que horário do dia acima você deseja que seja enviado o seu contrato?</label><label>Hora do Agendamento: </label><input class="form-control" type="time" name="time" value="08:00"></div></p></div>')
							document.getElementById('wish_today').value = 'não'

						}
						else {
							$('#second_checkbox').removeAttr('checked')
							$('#child').children('#não').remove();
							document.getElementById('wish_today').value = 'sim'
							$('#second_checkbox').attr('checked')
						}
					}
					$(document).on("change", "#id_date", function () {
						document.getElementById("id_end").min = this.value
						document.getElementById("id_expiration").min = this.value
					});
				</script>
				<script>(function(e,t,n){var r=e.querySelectorAll("html")[0];r.className=r.className.replace(/(^|\s)no-js(\s|$)/,"$1js$2")})(document,window,0);</script>

				{% endblock %}

classrooms/contract/templates/contract/select_student_to_contract.html
{% extends 'base.html'%}

{% block title %} Selecionar estudante para contrato {% endblock %}

{% block content %}

{% load static %}
<script>
	$(document).ready(function () {
		$('.container').removeClass('container');
	});
</script>

<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-9">
				<div class="card w-50">
					<div class="card-header">
						<h4 class="card-title" align="left">Selecionar estudante para contrato</h4>
					</div>
					<div class="card-body">
						<div class="row">
							<div class="col-md-11 pr-1">
								<div class="form-group">
									<form id="myForm" method="POST" class="" enctype="multipart/form-data"
										data-urlclasses="{% url 'users:classes_choices_ajax' %}"
										data-urlstudents="{% url 'users:students_choices_ajax' %}"> {% csrf_token %}
										<div style="margin-top: 10px">
											<p><label>Você deseja criar em lote?</label><br><label
													style="margin-right: 10px">Não</label><label class="switch">
													<input type="checkbox" id="first_checkbox">
													<a id="first_slider" class="slider round"></a>
												</label><label style="margin-left: 10px">Sim</label></p>
										</div>
										<div id="to_hide_schools" style="display: none;">
											<div class="labelandform">
												<p><label>Selecione a escola que você deseja criar contrato:</label></p>
												<select class="custom-select chosen-select" id="select_form_school">
													<option id="" value="0" selected>--------</option>
													{% for school in schools %}
													<option value="{{ school.school_id }}">{{ school.school_name }}
													</option>
													{% endfor %}
												</select>
											</div>
											<div class="labelandform">
												<p><label>Selecione a Turma:</label></p>
												<select class="custom-select" id="select_form_class">
													<option id="" value="0" selected>--------</option>
												</select>
											</div>
											<input type="hidden" id="selected_school" name="selected_school">
											<input type="hidden" id="selected_class" name="selected_class">
										</div>
										<div id="to_hide_students">
											<p>Selecione o(s) Estudante(s)</p>
											<select id="select_form" class="form-control chosen-select">
												<option id="" value="0" selected>--------</option>
												{% for student in students %}
												<option value="{{ student.student_id }}">{{ student.school_name }} - {{ student.name }}</option>
												{% endfor %}
											</select><br>
										</div>
										<input type="hidden" id="selected_user" name="selected_user">


										<div><button type="submit" class="btn btn-info btn-fill btn-sm pull-left mt-2"
												style="background-color: #213f99; border-color: #213f99">Próximo</button>
										</div>

									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).on("click", "#first_slider", function () {
		if (!$('#first_checkbox').prop("checked")) {
			$('#first_checkbox').attr('checked')
			$('#to_hide_schools').show();
			$('#to_hide_students').hide();
			selected_user = document.getElementById('selected_user')
			if (selected_user.value) {
				document.getElementById('selected_user').removeAttribute('value');
			}
		}
		else {
			$('#first_checkbox').removeAttr('checked')
			$('#to_hide_schools').hide();
			$('#to_hide_students').show();
			selected_school = document.getElementById('selected_school');
			if (selected_school.value) {
				document.getElementById('selected_school').removeAttribute('value');
			}
			selected_class = document.getElementById('selected_class')
			if (selected_class.value) {
				document.getElementById('selected_class').removeAttribute('value');
			}
		}
		$('#select_form_chosen').attr('style', 'width: 100%;');
		$('#select_form_school_chosen').attr('style', 'width: 100%;');
	});
	$(document).ready(function () {
		$('#select_form_school').on('change', function () {
			let urlClasses = $('#myForm').data('urlclasses')
			var selectValor = $(this).val();
			$.ajax({
				url: urlClasses,
				data: {
					id: selectValor
				},
				success: function (response) {
					$('#select_form_class').html(response)
				}
			})
			if (selectValor == '') {
				document.getElementById('selected_school').value = '0'
			}
			else {
				document.getElementById('selected_school').value = selectValor
			}
			document.getElementById('selected_user').removeAttribute('value')
		});
	});

	$(document).ready(function () {
		$('#select_form_class').on('change', function () {
			var selectValor = $(this).val();
			if (selectValor == '') {
				document.getElementById('selected_class').value = '0'
			}
			else {
				document.getElementById('selected_class').value = selectValor
			}
			document.getElementById('selected_user').removeAttribute('value')
		});
	});

	$(document).ready(function () {
		$('#select_form').on('change', function () {
			var selectValor = $(this).val();
			if (selectValor == '') {
				document.getElementById('selected_user').value = '0'
			}
			else {
				document.getElementById('selected_user').value = selectValor
			}
		});
	});
	$(document).ready(function () {
		$('#first_input').on('change', function () {
			var selectValor = $(this).val($(this).is(':checked'));
			if (selectValor == '') {
				$('#pai').children('div').remove();
				$('#child').children('div').remove();
			}
			else if (selectValor == true) {

			}
			else if (selectValor == false) {
				$('#pai').children('div').remove();
				$('#child').children('div').remove();
				document.getElementById('wish').value = 'não'
				document.getElementById('wish_today').value = 'não'
			}
		});
	});
	function select() {
		if (!$('#second_checkbox').prop("checked")) {
			$('#child').append('<div id="não"><p><div class="form-group"><label>Que dia você deseja que seja enviado o seu contrato?</label><label>Data do Agendamento: </label><input class="labelandform" type="date" name="date" style="width:120%"></div></p></div>')
			document.getElementById('wish_today').value = 'não'

		}
		else {
			$('#second_checkbox').removeAttr('checked')
			$('#child').children('#não').remove();
			document.getElementById('wish_today').value = 'sim'
			$('#second_checkbox').attr('checked')
		}
	}
</script>

{% endblock %}