classrooms/block/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views

router = routers.DefaultRouter()
router.register(r'chains', views.ChainViewSet)

urlpatterns = [
	url('', include(router.urls)),
    url(r'^blocks/(?P<chain_name>[A-Za-z0-9-]+)/latest$', views.LatestBlockApiView.as_view(), name='latest-block'),
    url(r'^blocks/(?P<chain_name>[A-Za-z0-9-]+)/mine-block$', views.BlockCreateView.as_view(), name='mine-block'),
    url(r'^blocks/(?P<hash>[A-Za-z0-9-]+)$', views.BlockApiView.as_view(), name='get'),
    url(r'^chains/(?P<name>[A-Za-z0-9-]+)$', views.ChainApiView.as_view(), name='chain'),
    url(r'^peers/$', views.PeerApiView.as_view(), name='peers'),
    url(r'^peers/add$', views.PeerApiView.as_view(), name='add-peer'),
    url(r'^transaction/$', views.TransactionsList.as_view(), name='transaction'),
]

classrooms/classrooms/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from classrooms import settings
from school.views import seeallschoolsbyquery
from django.views.static import serve 

urlpatterns = [
    path('datawizard/', include('data_wizard.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin_url/', admin.site.urls),
    url(r'^$', seeallschoolsbyquery),
    url('chain/', include('block.urls')),
    url('contracts/', include('contract.urls')),
    url('schools/', include('school.urls')),
    url('users/', include('school_users.urls')),
]
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

handler404 = 'school_users.views.handler404'
handler500 = 'school_users.views.handler500'

classrooms/contract/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views
from classrooms import settings

router = routers.DefaultRouter()
router.register(r'contracts', views.ContractsViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'contracts'
urlpatterns = [
    url('', include(router.urls)),
    path('mark_slm_purchased/<int:contract_id>', views.mark_slm_purchased, name="mark_slm_purchased"),
    url('createacontract/', views.createacontract, name="createacontract"),
    url('createacontract_rest/', views.createacontract_rest, name="createacontract_rest"),
    path('seecontractdetails/<int:contract_id>', views.seecontractdetails, name="seecontractdetails"),
    path('select_director_to_contract/<int:contract_id>', views.select_director_to_contract, name="select_director_to_contract"),
    url('all/', views.seecontractsbyquery, name="seemycontracts"),
    url('all_rest/', views.seemycontracts_rest, name="seemycontracts_rest"),
    path('set_signed/<int:contract_id>', views.set_signed, name='set_signed'),
    path('queue_set_signed/<int:contract_id>', views.queue_set_signed, name='queue_set_signed'),
    path('set_signed_rest/<int:contract_id>', views.set_signed_rest, name='set_signed_rest'),
    path('updatecontract/<int:contract_id>', views.updatecontract, name='updatecontract'),
    path('delete_contract/<int:contract_id>', views.delete_contract, name='delete_contract'),
    path('redirect_to_slm_link/<int:contract_id>', views.redirect_to_slm_link, name='redirect_to_slm_link'),
    path('seefinancialdetails/', views.seefinancialdetails, name='seefinancialdetails'),
    url('select_student_to_contract/', views.select_student_to_contract, name='select_student_to_contract'),
    path('select_student_to_contract_update/<int:contract_id>', views.select_student_to_contract_update, name='select_student_to_contract_update'),
    path(r'serve_protected/{}<path>/<int:contract_id>/<type_of_document>'.format(settings.MEDIA_URL[1:]), views.protected_serve, {'document_root': settings.MEDIA_ROOT}, name='serve_protected'),
    path('set_contract_paid/<int:contract_id>', views.set_contract_paid, name='set_contract_paid'),
    path('directors/ajax', views.directors_choices_ajax, name='directors_choices_ajax'),
    path('receive_maple_result/', views.receive_maple_result, name='receive_maple_result'),
    path('authenticated/', views.authenticated_google, name='authenticated'),
    path('upload_contract_file_to_drive/<int:contract_id>/<type_of_file>', views.upload_contract_file_to_drive, name='upload_contract_file_to_drive'),
    path('extend_expire_date/<int:contract_id>', views.extend_expire_date, name='extend_expire_date'),
    path('edit_dates/<int:contract_id>', views.edit_dates, name='edit_dates'),
]

classrooms/school/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views

router = routers.DefaultRouter()
router.register(r'schools', views.SchoolsViewSet)
router.register(r'schools_minimal', views.SchoolsViewSetMinimal)


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'school'
urlpatterns = [
    url('', include(router.urls)),
    url('import_xml/', views.import_xml, name='import_xml'),
    url('import_sponte/', views.import_sponte, name='import_sponte'),
    url('seeallschoolsbyquery/', views.seeallschoolsbyquery, name='seeallschoolsbyquery'),
    url('seeallclassesbyquery/', views.seeallclassesbyquery, name='seeallclassesbyquery'),
    path('seeclassbyid/<int:class_id>', views.seeclassbyid, name="seeclassbyid"),
    path('blockchain/<int:chain_id>', views.seechainbyid, name="seechainbyid"),
    url('add_school/', views.create_school, name="add_school"),
    url('seeallschools/', views.seeallschools, name="seeallschools"),
    url('select_school/', views.select_school, name="select_school"),
    path('seeschooldetails/<int:school_id>', views.seeschooldetails, name="seeschooldetails"),
    url('seeallschools_rest/', views.seeallschools_rest),
    path('update_school/<int:school_id>', views.update_school, name='update_school'),
    path('update_school_rest/<int:school_id>', views.update_school_rest, name='update_school_rest'),
    path('delete_school/<int:school_id>', views.delete_school, name='delete_school'),
    path('delete_school_rest/<int:school_id>', views.delete_school_rest, name='delete_school_rest'),
    path('<int:school_id>/add_class', views.add_class, name='add_class'),
    path('<int:school_id>/add_another_class', views.add_another_class, name='add_another_class'),
    path('<int:school_id>/add_another_class/add_students_for_multiple_classes', views.add_students_for_multiple_classes, name='add_students_for_multiple_classes'),
    path('<int:school_id>/add_another_class/select_class_to_add_students', views.select_class_to_add_students, name='select_class_to_add_students'),
    path('<int:school_id>/add_another_class/<int:class_id>/add_multiple_students', views.add_multple_students_for_class_and_school, name='add_multple_students_for_class_and_school'),
    path('<int:school_id>/add_first_witness', views.add_first_witness, name='add_first_witness'),
    path('<int:school_id>/add_second_witness', views.add_second_witness, name='add_second_witness'),
    path('<int:school_id>/add_witness/<type_of_user>', views.add_witness, name='add_witness'),
    path('<int:school_id>/set_witnesses', views.set_witnesses, name='set_witnesses'),
    path('<int:school_id>/add_class/<int:class_id>/add_student', views.add_student_to_class_and_school, name='add_student_to_class_and_school'),
    path('<int:school_id>/add_class/<int:class_id>/add_multiple_students', views.add_students_to_class_and_school, name='add_students_to_class_and_school'),
    path('<int:school_id>/add_class/<int:class_id>/add_student/<int:student_id>/add_first_parent_to_student', views.add_first_parent_to_student, name='add_first_parent_to_student'),
    path('<int:school_id>/add_class/<int:class_id>/add_student/<int:student_id>/add_second_parent_to_student', views.add_second_parent_to_student, name='add_second_parent_to_student'),
    path('add_students_to_school/<int:school_id>', views.add_students_to_school, name='add_students_to_school'),
    path('add_teachers_to_school/<int:school_id>', views.add_teachers_to_school, name='add_teachers_to_school'),
    path('add_teachers_to_class/<int:class_id>', views.add_teachers_to_class, name='add_teacher_to_class'),
    path('add_students_to_class/<int:class_id>', views.add_students_to_class, name='add_student_to_class'),
    path('add_class_rest/<int:school_id>', views.add_class_rest, name='add_class_rest'),
    path('update_class/<int:class_id>', views.update_class, name='update_class'),
    path('verifyvalidchain/<int:class_id>', views.verifyvalidchain, name='verifyvalidchain'),
    path('delete_class/<int:class_id>', views.delete_class, name='delete_class'),
    url('create_block/', views.create_block, name='create_block'),
    path('<int:school_id>/pull_students', views.pull_students, name='pull_students'),
    path('<int:school_id>/remove_non_active', views.remove_non_active_students, name='remove_non_active'),

]

classrooms/school/models.py
from django.db import models
from django.db.models import Q
from school_users.models import Student, Teacher, Head, Supervisor, Parent, Witness
from contract.models import Contract
from block.models import Chain

# Create your models here.


class School(models.Model):
    """docstring for School"""
    school_id = models.AutoField(primary_key=True)
    school_name = models.TextField(verbose_name='Nome da escola')
    classes = models.ManyToManyField('Class')
    chains = models.ManyToManyField(Chain)
    heads = models.ManyToManyField(Head, verbose_name='Diretores')
    adminorsupervisor = models.ForeignKey(
        Supervisor, on_delete=models.SET_NULL, verbose_name='Admin/Supervisor', null=True, blank=True)
    adminorsupervisor_2 = models.ForeignKey(Supervisor, on_delete=models.SET_NULL,
                                            verbose_name='Admin/Supervisor_2', null=True, blank=True, related_name='adminorsupervisor_2')
    sponte_client_number = models.IntegerField(
        null=True, blank=True, verbose_name='SPONTE ID')
    sponte_token = models.TextField(
        null=True, blank=True, verbose_name='SPONTE Token')
    tell_me_school_id = models.IntegerField(
        null=True, blank=True, verbose_name='TellMe ID')
    country = models.TextField(null=True, blank=True, verbose_name='País')
    state = models.TextField(null=True, blank=True, verbose_name='Estado')
    city = models.TextField(null=True, blank=True, verbose_name='Cidade')
    quantity_of_directors = models.IntegerField(
        null=True, blank=True, default=1, verbose_name='Quantidade de Diretores')
    students = models.ManyToManyField(
        Student, blank=True, verbose_name='Estudantes')
    teachers = models.ManyToManyField(Teacher)
    parents = models.ManyToManyField(Parent)
    first_witness = models.ForeignKey(Witness, on_delete=models.SET_NULL, verbose_name='Primeira Testemunha',
                                      null=True, blank=True, related_name='first_witness_school')
    second_witness = models.ForeignKey(Witness, on_delete=models.SET_NULL, verbose_name='Segunda Testemunha',
                                       null=True, blank=True, related_name='second_witness_school')
    app_name = models.TextField(
        null=True, blank=True, verbose_name='Nome do App')
    is_maple_bear = models.BooleanField(default=False)
    value_per_contract = models.FloatField(
        default=0.00, null=True, blank=True, verbose_name='Valor por Contrato')

    @property
    def quantity_of_contracts_signed(self):
        count = Contract.objects.filter(
            chain__in=self.chains.all(),
            first_auth_signed=True,
            second_auth_signed=True,
            counter_signed=True,
            all_signed=True
        ).count()
        return count

    @property
    def quantity_of_contracts_total(self):
        count = Contract.objects.filter(chain__in=self.chains.all()).count()
        return count

    @property
    def quantity_of_contracts_not_signed(self):
        count = Contract.objects.filter(chain__in=self.chains.all()).filter(
            Q(first_auth_signed=False) |
            Q(second_auth_signed=False) |
            Q(counter_signed=False) |
            Q(all_signed=False)
        ).count()
        return count

    @property
    def quantity_of_students_associated(self):
        return self.students.all().count()

    @property
    def quantity_of_parents_associated(self):
        count = Parent.objects.filter(
            Q(first_parent__in=self.students.all()) |
            Q(second_parent__in=self.students.all())
        ).distinct('pk').count()
        return count

    def __str__(self):
        return self.school_name


class Class(models.Model):
    """docstring for Class"""
    class_id = models.AutoField(primary_key=True)
    class_name = models.TextField(verbose_name='Nome da turma')
    CLASS_UNIT_CHOICES = [('Integral', 'Integral'), ('Manhã',
                                                     'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')]
    class_unit = models.CharField(max_length=500, choices=CLASS_UNIT_CHOICES,
                                  default='Integral', null=True, verbose_name='Horário')
    enrollment_class_year = models.IntegerField(verbose_name='Ano da turma')
    slm = models.TextField(null=True, blank=True, verbose_name='Materiais URL')
    sku = models.TextField(null=True, blank=True,
                           verbose_name='SKU do Material')
    students = models.ManyToManyField(
        Student, blank=True, verbose_name='Estudantes')
    teachers = models.ManyToManyField(Teacher)

    def __str__(self):
        return self.class_name

    @property
    def registered_contracts(self):
        school = self.school_set.all().first()
        chain = school.chains.get(name="{0}-{1}-{2}-{3}".format(
            school.school_name, self.enrollment_class_year, self.class_unit, self.class_name))
        registered_contracts = Contract.objects.filter(chain=chain).count()
        return registered_contracts

    @property
    def complete_contracts(self):
        school = self.school_set.all().first()
        chain = school.chains.get(name="{0}-{1}-{2}-{3}".format(
            school.school_name, self.enrollment_class_year, self.class_unit, self.class_name))
        registered_contracts = Contract.objects.filter(
            chain=chain, all_signed=True).count()
        return registered_contracts

    @property
    def quantity_of_students_associated(self):
        return self.students.all().count()

    @property
    def quantity_of_parents_associated(self):
        count = 0
        for student in self.students.all():
            if student.first_parent:
                count += 1
            if student.second_parent:
                count += 1
        return count

    def preliminary_students(self):
        """Remember to do this as well later, confirm student"""
        pass

classrooms/school/templates/school/seeallschools.html
{% extends 'base.html'%}

{% block title %} Ver Todas as Escolas {% endblock %}

{% block content %}

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card strpied-tabled-with-hover">

          <div class="card-header ">
            <h4 class="card-title">Escola(s)</h4>
          </div>

          <div class="card-body table-full-width table-responsive">
            <table class="table table-hover table-striped" id="schoolstable">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>
                    Contratos <br>
                    Assinados
                  </th>
                  <!-- <th>Contratos Não Assinados</th> -->
                  <th>
                    Número de <br>
                    Alunos <br>
                    Associados
                  </th>
                  <th>
                    Número de Pais/Mães <br>
                    Associados
                  </th>
                  <th>Turmas</th>
                  <th>Blockchain</th>
                </tr>
              </thead>
              <tbody>
                {% for school in schools %}
                <tr>
                  <th>{{ school.school_name }}

                    <div class="dropdown show">
                      <a class="btn btn-danger dropdown-toggle btn-sm" href="#" role="button" id="dropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Ações
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'school:add_class' school.school_id %}"
                          data-baloon="Remove this item from the cart" class="text-danger">Adicionar Turma à Escola</a>
                        <a class="dropdown-item" href="{% url 'school:set_witnesses' school.school_id %}"
                          data-baloon="Remove this item from the cart" class="text-danger">Selecionar Testemunhas Para Escola</a>
                        <!-- <a class="dropdown-item" href="{% url 'school:add_students_to_school' school.school_id %}"
                          data-baloon="Remove this item from the cart" class="text-danger">Selecionar Estudantes Para
                          Escola</a> -->
                        <!-- <a class="dropdown-item"href="{% url 'school:add_teachers_to_school' school.school_id %}" data-baloon="Remove this item from the cart" class="text-danger">Selecionar Professores Para Escola</a> -->
                        <a class="dropdown-item" href="{% url 'school:update_school' school.school_id %}" data-baloon="Remove this item from the cart" class="text-danger">Atualizar Escola</a>
                        {% if request.user.is_superuser %}
                          <a class="dropdown-item" href="{% url 'school:delete_school' school.school_id %}" data-baloon="Remove this item from the cart" class="text-danger">Deletar Escola</a>
                        {% endif %}
                        {% if request.user.is_superuser or is_supervisor %}
                        <a class="dropdown-item" href="{% url 'school:seeschooldetails' school.school_id %}"
                          data-baloon="Remove this item from the cart" class="text-danger">Ver Detalhes da Escola</a>
                        {% endif %}
                      </div>
                    </div>
                  </th>

                  <th>{{ school.quantity_of_contracts_signed }}/{{ school.quantity_of_contracts_total }}</th>
                  <!-- <th>{{ school.quantity_of_contracts_not_signed }}/{{ school.quantity_of_contracts_total }}</th> -->
                  <th>{{ school.quantity_of_students_associated }}</th>
                  <th>{{ school.quantity_of_parents_associated }}</th>

                  {% if school.classes %}
                  <td>

                    <div class="flex-column-alignment"  style="width: 100%">
                    {% for class in school.classes.all|dictsort:"class_id" %}

                    <div class="row width-full margin-bottom-5">
                      <div class="col-md-6">
                        <label>{{ class.class_name }}, {{ class.enrollment_class_year }}</label>
                      </div>

                      <div class="col-md-6">
                        <div class="dropdown show">
                          <a class="btn btn-danger dropdown-toggle btn-sm" href="" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Ações
                          </a>
    
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'school:verifyvalidchain' class.class_id %}"
                              data-baloon="Remove this item from the cart" class="text-danger">Verificar Validade do Blockchain
                              Para a Turma</a>
                            <!-- <a class="dropdown-item" href="{% url 'school:add_student_to_class' class.class_id %}"
                              data-baloon="Remove this item from the cart" class="text-danger">Selecionar Estudantes Para
                              Turma</a> -->
                            <!-- <a class="dropdown-item" href="{% url 'school:add_teacher_to_class' class.class_id %}" data-baloon="Remove this item from the cart" class="text-danger">Selecionar Professores Para Turma</a> -->
                            <a class="dropdown-item" href="{% url 'school:update_class' class.class_id %}"
                              data-baloon="Remove this item from the cart" class="text-danger">Atualizar Turma</a>
                            <a class="dropdown-item" href="{% url 'school:delete_class' class.class_id %}"
                              data-baloon="Remove this item from the cart" class="text-danger">Deletar Turma</a>
                            <a class="dropdown-item" href="{% url 'school:seeclassbyid' class.class_id %}"
                              data-baloon="Remove this item from the cart" class="text-danger">Ver Detalhes da Turma</a>
                          </div>
                        </div>
                      </div>

                    </div>

                    {% endfor %}
                    </div>
                  </td>
                  {% endif %}
                  {% if school.chains %}
                  <td  style="width: 100%;">
                    <div class="flex-column-alignment">
                      {% for chain in school.chains.all|dictsort:"id" %}
                      <div class="row width-full margin-bottom-5">
  
                        <div class="col-md-6">
                          <label>{{ chain.name }}</label>
                        </div>
                        <div class="col-md-6">
                          <a class="btn btn-secondary btn-sm" href="{% url 'school:seechainbyid' chain.id %}"
                            role="button" data-baloon="Remove this item from the cart" class="text-danger">Ver Blockchain</a>
                        </div>
  
                      </div>
                      
                      {% endfor %}
                    </div>

                  </td>
                  {% endif %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    var dt = $('#schoolstable').DataTable();
    $(window).on('resize', function () {
      $('#schoolstable').DataTable();
    })
  });
</script>
{% endblock %}

classrooms/school/templates/school/seechainbyname.html
{% extends 'base.html'%}

{% block title %} Chain Details {% endblock %}

{% block content %}

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card strpied-tabled-with-hover">
          <div class="card-header ">
            <h4 class="card-title">{{ chain.name }}</h4>
            <p class="card-category">{{ chain.time_stamp }}</p>
          </div>
          <div class="card-body table-full-width table-responsive">
            <table class="table table-hover table-striped" id="schoolstable">
              <thead>
                <tr>

                  <th style="pointer-events: none;">Blocos</th>
                  

                </tr>
              </thead>
              <tbody style="word-break: break-word;">
                {% if chain.block_set %}
                {% for block in chain.block_set.all %}
                <tr>

                  <td align="center" style="display: block;">


                    <div class="chain-colors" align="center" class="mb-5" style="width: 70%">


                      <div style="border-style: solid; display: block; width: 100%;">
                        <h4><b>Índice do Bloco:</b> {{ block.index }}</h4>
                        <h4>{{ block.contract.name }}</h4>
                        <div style="margin-left: auto; margin-right: auto; word-wrap: none; white-space: nowrap;">
                          <b>Hash:</b> {{ block.hash }}
                        </div>
                        <div style="margin-left: auto; margin-right: auto;  word-wrap: none; white-space: nowrap;">
                          <b>Hash Anterior:</b> {{ block.previous_hash }}
                        </div>
                        <div style="margin-left: auto; margin-right: auto;">
                          <b>Data e Hora:</b> {{ block.time_stamp.day }}/{{ block.time_stamp.month }}/{{block.time_stamp.year }} às {% if block.time_stamp.hour < 10 %}0{{ block.time_stamp.hour }}{% else %}{{block.time_stamp.hour}}{% endif %}:{% if block.time_stamp.minute < 10 %}0{{ block.time_stamp.minute }}{% else %}{{ block.time_stamp.minute }}{% endif %}:{% if block.time_stamp.second < 10 %}0{{ block.time_stamp.second }}{% else %}{{ block.time_stamp.second }}{% endif %}
                        </div>
                        <div style="margin-left: auto; margin-right: auto;">
                          <b>Nó do Bloco:</b> {{ block.nonce }}
                        </div>
                        <div style="margin-left: auto; margin-right: auto;">
                          <b>Estudante associado ao bloco:</b> {{ block.contract.student_name }}
                        </div>
                        <div style="margin-left: auto; margin-right: auto;">
                          <b>Contrato do bloco:</b>
                            <a href="{% url 'contracts:serve_protected' block.contract.pdf.name block.contract.contract_id 'contract' %}" data-baloon="Remove this item from the cart">
                                  <!-- {{ contract.pdf }} -->
                                  Link
                                </a>
                        </div>
                        {% if block.contract.terms_of_contract %}
                        <div style="margin-left: auto; margin-right: auto;">
                          <b>Termos aditivos do contrato (1) do bloco:</b>
                            <a href="{% url 'contracts:serve_protected' block.contract.terms_of_contract.name block.contract.contract_id 'terms_1' %}" data-baloon="Remove this item from the cart">
                                  <!-- {{ contract.pdf }} -->
                                  Link
                                </a>
                        </div>
                        {% endif %}
                        {% if block.contract.terms_of_contract_2 %}
                        <div style="margin-left: auto; margin-right: auto;">
                          <b>Termos aditivos do contrato (2) do bloco:</b>
                            <a href="{% url 'contracts:serve_protected' block.contract.terms_of_contract_2.name block.contract.contract_id 'terms_2' %}" data-baloon="Remove this item from the cart">
                                  <!-- {{ contract.pdf }} -->
                                  Link
                                </a>
                        </div>
                        {% endif %}
                        <div style="margin-left: auto; margin-right: auto;">
                          <b>Quem assinou o contrato:</b>
                            {% if block.hash == block.contract.first_auth_hash %}
                            {{ block.contract.first_auth_signe.name }}
                            {% elif block.hash == block.contract.second_auth_hash %}
                            {{ block.contract.second_auth_signe.name }}
                            {% elif block.hash == block.contract.counter_auth_hash %}
                            {{ block.contract.counter_signe.name }}
                          {% endif %}
                        </div>    
                      </div>

                      {% if forloop.counter0 == chain.block_set.count %}

                      {% else %}
                        {% if not forloop.first %}
                        <!--Arrow--> 
                        <i style="font-size:40px" align="center" class="fas fa-long-arrow-alt-down mt-1"></i>
                        {% endif %}
                      {% endif %}
                    </div>



                  </td>

                </tr>
                {% endfor %}
                {% endif %}
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    $('#schoolstable').DataTable();
  });
</script>
{% endblock %}

classrooms/school/templates/school/set_witnesses.html
{% extends 'base.html'%}

{% block title %} Selecionar Testemunhas {% endblock %}

{% block content %}
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-9">
				<div class="card w-50">
					<div class="card-header">
						<h4 class="card-title">Selecionar Testemunhas</h4>
					</div>
					<div class="card-body">
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<form method="POST">{% csrf_token %}
										<p>
											<label for="id_first_witness">{{ form.first_witness.label }}:</label>

											<div class="row">
												<div class="col-9">
													{{ form.first_witness }}
												</div>
												<div class="col-2">
													<a class="box-rounded flex-div box-rounded-blue color-link-white vertical-align-with-transform" href="{% url 'school:add_witness' school_id 'first_witness' %}">
														<p class="fas fa-plus centralize-margin font-size-plus"></p>
													</a>
												</div>
											</div>
										</p>
										<p>
											<label for="id_second_witness">{{ form.second_witness.label }}:</label>

											<div class="row">
												<div class="col-9">
													{{ form.second_witness }}
												</div>
												<div class="col-2">
													<a class="box-rounded flex-div box-rounded-blue color-link-white vertical-align-with-transform" href="{% url 'school:add_witness' school_id 'second_witness' %}">
														<p class="fas fa-plus centralize-margin font-size-plus"></p>
													</a>
												</div>
											</div>
										</p>
										<div>
											<button type="submit" class="btn btn-info btn-fill pull-left" style="background-color: #213f99; border-color: #213f99">
												Atualizar a	Escola
											</button>
										</div>
										<div class="clearfix"></div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

{% endblock %}