classrooms/block/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views

router = routers.DefaultRouter()
router.register(r'chains', views.ChainViewSet)

urlpatterns = [
	url('', include(router.urls)),
    url(r'^blocks/(?P<chain_name>[A-Za-z0-9-]+)/latest$', views.LatestBlockApiView.as_view(), name='latest-block'),
    url(r'^blocks/(?P<chain_name>[A-Za-z0-9-]+)/mine-block$', views.BlockCreateView.as_view(), name='mine-block'),
    url(r'^blocks/(?P<hash>[A-Za-z0-9-]+)$', views.BlockApiView.as_view(), name='get'),
    url(r'^chains/(?P<name>[A-Za-z0-9-]+)$', views.ChainApiView.as_view(), name='chain'),
    url(r'^peers/$', views.PeerApiView.as_view(), name='peers'),
    url(r'^peers/add$', views.PeerApiView.as_view(), name='add-peer'),
    url(r'^transaction/$', views.TransactionsList.as_view(), name='transaction'),
]

classrooms/classrooms/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from classrooms import settings
from school.views import seeallschoolsbyquery
from django.views.static import serve 

urlpatterns = [
    path('datawizard/', include('data_wizard.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin_url/', admin.site.urls),
    url(r'^$', seeallschoolsbyquery),
    url('chain/', include('block.urls')),
    url('contracts/', include('contract.urls')),
    url('schools/', include('school.urls')),
    url('users/', include('school_users.urls')),
]
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

handler404 = 'school_users.views.handler404'
handler500 = 'school_users.views.handler500'

classrooms/school_users/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from django.contrib.auth.views import PasswordResetView

# router = routers.DefaultRouter()
# router.register(r'schools', views.SchoolsViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'users'
urlpatterns = [
    # url('', include(router.urls)),
    url('create_user/', views.create_user, name="create_user"),
    url('all_administration/', views.seeusersbyquery_administration, name="all_administration"),
    url('all_signes/', views.seeusersbyquery_signes, name="all_signes"),
    path('all_by_school/<int:school_id>', views.seeallusers_by_school, name='seeallusers_by_school'),
    url('all_rest/', views.seeallusers_rest),
    path('delete_user/<int:user_id>/<type_of_user>', views.delete_user, name='delete_user'),
    path('set_parents/<int:student_id>/', views.set_parents, name='set_parents'),
    path('add_parent/<int:student_id>/<type_of_user>', views.add_parent, name='add_parent'),
    path('select_parent/<int:student_id>/<type_of_user>', views.select_parent, name='select_parent'),
    path('confirm_parent/<int:student_id>/<int:parent_id>/<type_of_user>', views.confirm_parent, name='confirm_parent'),
    path('add_first_parent/<int:student_id>', views.add_first_parent, name='add_first_parent'),
    path('add_second_parent/<int:student_id>', views.add_second_parent, name='add_second_parent'),
    path('classes/ajax', views.classes_choices_ajax, name='classes_choices_ajax'),
    path('students/ajax', views.students_choices_ajax, name='students_choices_ajax'),
    url('add_student/', views.add_student, name='add_student'),
    url('login/', views.do_login, name='login'),
    path('login_from_other_system/<username>', views.login_from_other_system, name='login_from_other_system'),
    url('logout', views.do_logout, name='logout'),
    url('api/login', obtain_jwt_token, name='login_rest'),
    url('api/refresh_token', refresh_jwt_token, name='refresh_token'),
    url('current_user/', views.current_user, name='current_user'),
    path('create_head_to_school/<int:school_id>', views.create_head_to_school, name='create_head_to_school'),
    path('create_supervisor_to_school/<int:school_id>', views.create_supervisor_to_school, name='create_supervisor_to_school'),
    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.reset_password, name='reset_password'),
    url('generate_password', views.generate_password, name='generate_password'),
    url('profile', views.profile, name='profile'),
    url('update_perfil', views.update_profile, name='update_perfil'),
    path('do_u_need_parents/<int:student_id>/<int:school_id>/<int:class_id>', views.do_u_need_parents, name='do_u_need_parents'),
    path('seesonsofparent/<int:parent_id>', views.seesonsofparent, name='seesonsofparent'),
    path('reset_password_send_email/<int:user_id>/<type_of_user>', views.reset_password_send_email, name='reset_password_send_email'),
    path('change_email/<user_id>', views.change_email, name='change_email'),
    path('room/<str:room_name>/', views.room, name='room'),
    url('forgot_password', views.forgot_password, name='forgot_password'),
]

classrooms/school/models.py
from django.db import models
from django.db.models import Q
from school_users.models import Student, Teacher, Head, Supervisor, Parent, Witness
from contract.models import Contract
from block.models import Chain

# Create your models here.


class School(models.Model):
    """docstring for School"""
    school_id = models.AutoField(primary_key=True)
    school_name = models.TextField(verbose_name='Nome da escola')
    classes = models.ManyToManyField('Class')
    chains = models.ManyToManyField(Chain)
    heads = models.ManyToManyField(Head, verbose_name='Diretores')
    adminorsupervisor = models.ForeignKey(
        Supervisor, on_delete=models.SET_NULL, verbose_name='Admin/Supervisor', null=True, blank=True)
    adminorsupervisor_2 = models.ForeignKey(Supervisor, on_delete=models.SET_NULL,
                                            verbose_name='Admin/Supervisor_2', null=True, blank=True, related_name='adminorsupervisor_2')
    sponte_client_number = models.IntegerField(
        null=True, blank=True, verbose_name='SPONTE ID')
    sponte_token = models.TextField(
        null=True, blank=True, verbose_name='SPONTE Token')
    tell_me_school_id = models.IntegerField(
        null=True, blank=True, verbose_name='TellMe ID')
    country = models.TextField(null=True, blank=True, verbose_name='País')
    state = models.TextField(null=True, blank=True, verbose_name='Estado')
    city = models.TextField(null=True, blank=True, verbose_name='Cidade')
    quantity_of_directors = models.IntegerField(
        null=True, blank=True, default=1, verbose_name='Quantidade de Diretores')
    students = models.ManyToManyField(
        Student, blank=True, verbose_name='Estudantes')
    teachers = models.ManyToManyField(Teacher)
    parents = models.ManyToManyField(Parent)
    first_witness = models.ForeignKey(Witness, on_delete=models.SET_NULL, verbose_name='Primeira Testemunha',
                                      null=True, blank=True, related_name='first_witness_school')
    second_witness = models.ForeignKey(Witness, on_delete=models.SET_NULL, verbose_name='Segunda Testemunha',
                                       null=True, blank=True, related_name='second_witness_school')
    app_name = models.TextField(
        null=True, blank=True, verbose_name='Nome do App')
    is_maple_bear = models.BooleanField(default=False)
    value_per_contract = models.FloatField(
        default=0.00, null=True, blank=True, verbose_name='Valor por Contrato')

    @property
    def quantity_of_contracts_signed(self):
        count = Contract.objects.filter(
            chain__in=self.chains.all(),
            first_auth_signed=True,
            second_auth_signed=True,
            counter_signed=True,
            all_signed=True
        ).count()
        return count

    @property
    def quantity_of_contracts_total(self):
        count = Contract.objects.filter(chain__in=self.chains.all()).count()
        return count

    @property
    def quantity_of_contracts_not_signed(self):
        count = Contract.objects.filter(chain__in=self.chains.all()).filter(
            Q(first_auth_signed=False) |
            Q(second_auth_signed=False) |
            Q(counter_signed=False) |
            Q(all_signed=False)
        ).count()
        return count

    @property
    def quantity_of_students_associated(self):
        return self.students.all().count()

    @property
    def quantity_of_parents_associated(self):
        count = Parent.objects.filter(
            Q(first_parent__in=self.students.all()) |
            Q(second_parent__in=self.students.all())
        ).distinct('pk').count()
        return count

    def __str__(self):
        return self.school_name


class Class(models.Model):
    """docstring for Class"""
    class_id = models.AutoField(primary_key=True)
    class_name = models.TextField(verbose_name='Nome da turma')
    CLASS_UNIT_CHOICES = [('Integral', 'Integral'), ('Manhã',
                                                     'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')]
    class_unit = models.CharField(max_length=500, choices=CLASS_UNIT_CHOICES,
                                  default='Integral', null=True, verbose_name='Horário')
    enrollment_class_year = models.IntegerField(verbose_name='Ano da turma')
    slm = models.TextField(null=True, blank=True, verbose_name='Materiais URL')
    sku = models.TextField(null=True, blank=True,
                           verbose_name='SKU do Material')
    students = models.ManyToManyField(
        Student, blank=True, verbose_name='Estudantes')
    teachers = models.ManyToManyField(Teacher)

    def __str__(self):
        return self.class_name

    @property
    def registered_contracts(self):
        school = self.school_set.all().first()
        chain = school.chains.get(name="{0}-{1}-{2}-{3}".format(
            school.school_name, self.enrollment_class_year, self.class_unit, self.class_name))
        registered_contracts = Contract.objects.filter(chain=chain).count()
        return registered_contracts

    @property
    def complete_contracts(self):
        school = self.school_set.all().first()
        chain = school.chains.get(name="{0}-{1}-{2}-{3}".format(
            school.school_name, self.enrollment_class_year, self.class_unit, self.class_name))
        registered_contracts = Contract.objects.filter(
            chain=chain, all_signed=True).count()
        return registered_contracts

    @property
    def quantity_of_students_associated(self):
        return self.students.all().count()

    @property
    def quantity_of_parents_associated(self):
        count = 0
        for student in self.students.all():
            if student.first_parent:
                count += 1
            if student.second_parent:
                count += 1
        return count

    def preliminary_students(self):
        """Remember to do this as well later, confirm student"""
        pass

classrooms/school_users/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth.forms import UserCreationForm
import datetime

class UserModelForm(UserCreationForm, forms.ModelForm):
	"""docstring for UserModelForm"""
	email = forms.EmailField(required=True)
	first_name = forms.CharField(required=True)
	last_name = forms.CharField(required=True)
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', 'password1', 'password2')
		def save(self, commit=True):
			user = super(UserModelForm, self).save(commit=False)
			user.username = self.cleaned_data['username'].lower()
			user.first_name = self.cleaned_data['first_name']
			user.last_name = self.cleaned_data['last_name']
			user.email = self.cleaned_data['email'].lower()

			if commit:
				user.save()

			return user

class HeadModelForm(forms.ModelForm):
	"""docstring for ManagerModelForm"""
	class Meta:
		model = Head
		fields = []

class TeacherModelForm(forms.ModelForm):
	"""docstring for ManagerModelForm"""
	class Meta:
		model = Teacher
		fields = []

class AdminModelForm(forms.ModelForm):
	"""docstring for ManagerModelForm"""
	class Meta:
		model = Admin
		fields = []

class SupervisorModelForm(forms.ModelForm):
	"""docstring for ManagerModelForm"""
	class Meta:
		model = Supervisor
		fields = []

class ParentModelForm(forms.ModelForm):
	"""docstring for ManagerModelForm"""
	class Meta:
		model = Parent
		fields = ['maple_bear_username', 'maple_bear_password', 'maple_bear_email']
		widgets = {
			'maple_bear_username': forms.TextInput(attrs={'class':'form-control', 'required':False, 'maxlength':255}),
			'maple_bear_password': forms.TextInput(attrs={'type':'password','class':'form-control', 'required':False, 'maxlength':255}),
			'maple_bear_email': forms.TextInput(attrs={'class':'form-control', 'required':False, 'maxlength':255}),
		}

class ParentIdTellMeModelForm(forms.ModelForm):
	"""docstring for ParentIdTellMeModelForm"""
	class Meta:
		model = Parent
		fields = ['tell_me_user_id']
		

class StudentModelForm(forms.ModelForm):
	"""docstring for ManagerModelForm"""
	class Meta:
		model = Student
		fields = ['birthday', 'tell_me_user_id', 'financial_responsible_id_sponte', 'didatic_responsible_id_sponte']
		widgets = {
			'birthday': forms.DateInput(attrs={'type':'date', 'class':'form-control', 'required':True, 'style':"width:100%", 'max':datetime.date.today()-datetime.timedelta(days=1)}),
		}

class SetParentsModelForm(forms.ModelForm):
	"""docstring for ManagerModelForm"""
	class Meta:
		model = Student
		fields = ['first_parent','second_parent', 'third_parent']
		widgets = {
			'first_parent': forms.Select(attrs={'class':'form-control chosen-select'}),
			'second_parent': forms.Select(attrs={'class':'form-control chosen-select'}),
			'third_parent': forms.Select(attrs={'class':'form-control chosen-select'}),
		}

class ProfileForStudentModelForm(forms.ModelForm):
	"""docstring for ProfileForStudentModelForm"""
	class Meta:
		model = Student
		fields = ['maple_bear_username', 'maple_bear_password', 'maple_bear_email']
		widgets = {
			'maple_bear_username': forms.TextInput(attrs={'class':'form-control', 'required':False, 'maxlength':255}),
			'maple_bear_password': forms.TextInput(attrs={'type':'password','class':'form-control', 'required':False, 'maxlength':255}),
			'maple_bear_email': forms.TextInput(attrs={'class':'form-control', 'required':False, 'maxlength':255}),
		}

class WitnessModelForm(forms.ModelForm):
	"""docstring for WitnessModelForm"""
	class Meta:
		model = Witness
		fields = ['rg', 'cpf']
		widgets = {
			'rg': forms.TextInput(attrs={'class':'form-control', 'required':True, 'maxlength':255}),
			'cpf': forms.TextInput(attrs={'class':'form-control', 'required':True, 'maxlength':255}),
		}

class EmailModelForm(forms.ModelForm):
	"""docstring for EmailModelForm"""
	class Meta:
		model = User
		fields = ['email']

classrooms/school_users/templates/school_users/change_email.html
{% extends 'base.html'%}

{% block title %} Editar Email {% endblock %}

{% block content %}

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-9">
        <div class="card w-50">
          <div class="card-header">
            <h4 class="card-title">Editar Email</h4>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-11 pr-1">
                <div class="form-group">
                  <form method="POST" enctype="multipart/form-data" class=""> {% csrf_token %}
                    {{ form.as_p }}
                    <div>
                      <button class="btn btn-info btn-fill pull-left" type="submit"style="background-color: #213f99; border-color: #213f99">
                        Editar Email
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




<script type="text/javascript">
  $(document).ready( function () {
    $('#sonstable').DataTable();
    $('#teacherstable').DataTable();
    $('#parentstable').DataTable();
    $('#supervisorstable').DataTable();
    $('#headstable').DataTable();
    $('#adminstable').DataTable();
  } );
</script>
{% endblock %}

classrooms/school_users/templates/school_users/password.html
{{ password }}

classrooms/school_users/templates/school_users/seeusersbyquery_signes.html
{% extends 'base.html'%}

{% block title %} Pesquisar Assinantes {% endblock %}

{% block content %}
<script>
	$(document).ready(function () {
		$('.container').removeClass('container');
	});
	setGenPasswordToFields(['id_{{user_form.password1.name}}', 'id_{{user_form.password2.name}}']);
</script>


<div class="content">
	<div class="container-fluid">
		<div class="card">
			<div class="card-header">
				<h4 class="card-title">Filtros de Assinantes</h4>
			</div>
			<div class="card-body">
				<div class="form-group">
					<form id="myForm" method="POST" enctype="multipart/form-data"
						data-urlclasses="{% url 'users:classes_choices_ajax' %}"> {% csrf_token %}
						<div class="row">
							<div class="labelandform col-md-6">
								<p><label>Selecione a Escola:</label></p>
								<select class="custom-select chosen-select" id="select_form_school">
									<option id="" value="">Todas</option>
									{% for school in schools %}
									<option value="{{ school.school_id }}"
										{% if school.school_id == query.selected_school %} selected {% endif %}>
										{{ school.school_name }}
									</option>
									{% endfor %}
								</select>
							</div>
							<div class="labelandform col-md-6">
								<p><label>Selecione a Turma:</label></p>
								<select class="custom-select chosen-select" id="select_form_class">
									<option id="" value="0" selected>--------</option>
								</select>
							</div>
							<input type="hidden" id="selected_school" name="selected_school" {% if query.selected_school %}value="{{ query.selected_school }}"{% endif %}>
							<input type="hidden" id="selected_class" name="selected_class" {% if query.selected_class %}value="{{ query.selected_class }}"{% endif %}>
						</div>
						<div class="row">
							<div class="labelandform col-md-12">
								<p><label>Tipo de Usuário:</label></p>
								<select class="custom-select chosen-select" id="select_form">
									<option id="" value="" selected>Todos</option>
									<option value="parent" {% if query.type_of_user == 'parent' %} selected {% endif %}>
										Responsáveis</option>
									<option value="student" {% if query.type_of_user == 'student' %} selected
										{% endif %}>Estudante</option>
								</select>
							</div>
						</div>
						<input type="text" id="name" name="name" placeholder="Insira o nome do usuário aqui..."
							value="{{query.name}}">
						<input type="hidden" id="type_of_user" name="type_of_user" {% if query.type_of_user %}value="{{ query.type_of_user }}"{% endif %}>
						<p class="text-warning">{{error}}</p>
						<div style="margin-top: 10px">
							<button class="btn btn-info btn-fill pull-left" type="submit"
                                style="background-color: #3CB371; border-color: #3CB371">Buscar</button>
                            <input type="button" onClick="limpa()" class="btn btn-info btn-fill pull-left"
                                style="background-color: #B22222; border-color: #B22222; margin-left: 30px;"
								value="Limpar" />
							<input type="button" onClick="exportTableToCSV('Assinantes.csv')" class="btn btn-info btn-fill pull-left"
                                style="background-color: #1D23D7; border-color: #1D23D7; margin-left: 30px;"
                                value="Relatório" />
						</div>

					</form>
				</div>

			</div>
		</div>
	</div>
	<div class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div class="card strpied-tabled-with-hover">
						<div class="card-header ">
							<h4 class="card-title">Resultados</h4>
						</div>
						<div class="card-body table-full-width table-responsive">
							<table class="table table-hover table-striped display mb-4" id="headstable">
								<thead>
									<tr>
										{% if query.type_of_user == 'student' or not query.type_of_user %}
											<th>Escolas</th>
										{% elif query.type_of_user == 'parent' %}
											<th>Escolas</th>
										{% endif %}
										<th>Nome</th>
										{% if query.type_of_user == 'student' or not query.type_of_user %}
											<th>Turmas</th>
											<th>Responsáveis</th>
										{% endif %}
										<th>Ações</th>
									</tr>
								</thead>
								{% if school_users %}
								<tbody class="">
									{% for user in school_users %}
									<tr>
										<td>
											<div class="container" style="white-space: nowrap; text-align: center">
												{% for school in user.school_set.all %}
													<div class="row" style="margin-bottom: 10px">
														<div class="col-md-12">
															{{ school.school_name }}
														</div>
													</div>
												{% endfor %}
												{% if user.first_parent.all or user.second_parent.all or user.third_parent.all %}
													<div class="row" style="margin-bottom: 10px">
														<div class="col-md-12">
															{{ user.school_name }}
														</div>
													</div>
												{% endif %}
											</div>
										</td>
										<th>{{ user.name }}</th>
										{% if query.type_of_user == 'student' or not query.type_of_user %}
											<td>
												<div class="container" style="white-space: nowrap; text-align: center">
													{% for classe in user.class_set.all %}
														<div class="row" style="margin-bottom: 10px">
															<div class="col-md-12">
																{{ classe.class_name }}
															</div>
														</div>
													{% endfor %}
												</div>
											</td>
											<td>
												{% if user.first_parent.all or user.second_parent.all or user.third_parent.all %}
												{% else %}
													<div class="container" style="white-space: nowrap; text-align: center">
														{% if user.first_parent %}
															<div class="row" style="margin-bottom: 10px">
																<div class="col-md-12">
																	{{ user.first_parent.name }}
																</div>
															</div>
														{% endif %}
														{% if user.second_parent %}
															<div class="row" style="margin-bottom: 10px">
																<div class="col-md-12">
																	{{ user.second_parent.name }}
																</div>
															</div>
														{% endif %}
														{% if user.third_parent %}
															<div class="row" style="margin-bottom: 10px">
																<div class="col-md-12">
																	{{ user.third_parent.name }}
																</div>
															</div>
														{% endif %}
													</div>
												{% endif %}
											</td>
										{% endif %}
										<th>
											<div class="dropdown show">
												<button type="button" class="btn btn-secondary" id="dropdownMenuLink"
													data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i
														class="fas fa-ellipsis-h"></i></button>
			
			
												<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
													{% if user.first_parent.all or user.second_parent.all or user.third_parent.all %}
													{% else %}
															<a href="{% url 'users:set_parents' user.student_id %}"
																data-baloon="Remove this item from the cart"
																class="dropdown-item">
																Selecionar Responsáveis
															</a>
													{% endif %}
													{% if user.profile %}
														<a href="{% url 'users:change_email' user.profile.id %}"
														data-baloon="Remove this item from the cart"
														class="dropdown-item">Atualizar Email</a>
														{% if user.first_parent.all or user.second_parent.all or user.third_parent.all %}
														<a href="{% url 'users:reset_password_send_email' user.parent_id 'parent' %}"
															data-baloon="Remove this item from the cart"
															class="dropdown-item">Resetar Senha</a>
														{% else %}
														<a href="{% url 'users:reset_password_send_email' user.student_id 'student' %}"
															data-baloon="Remove this item from the cart"
															class="dropdown-item">Resetar Senha</a>
														{% endif %}
													{% endif %}
													{% if user.first_parent.all or user.second_parent.all or user.third_parent.all %}
														<a class="dropdown-item"
															onclick="changeYesLink('{% url 'users:delete_user' user.parent_id 'parent' %}')"
															href="#" data-baloon="Remove this item from the cart"
															class="text-light" data-toggle="modal"
															data-target="#delete-assinante-modal">
															Deletar Responsável
														</a>
													{% else %}
														<a class="dropdown-item"
															onclick="changeYesLink('{% url 'users:delete_user' user.student_id 'student' %}')"
															href="#" data-baloon="Remove this item from the cart"
															class="text-light" data-toggle="modal"
															data-target="#delete-assinante-modal">
															Deletar Estudante
														</a>
													{% endif %}
												</div>
											</div>
										</th>
									</tr>
									{% endfor %}
								</tbody>
								{% endif %}
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		function limpa() {
            document.getElementById('selected_school').value = "";
            document.getElementById('selected_class').value = "";
			document.getElementById('type_of_user').value = "";
			document.getElementById('name').value = "";
            $('#select_form_school')
                .find('option:first-child').prop('selected', true)
                .end().trigger('chosen:updated');
            $('#select_form_class').html(`<option id="" value="0">--------</option>`)
            $('#select_form_class')
                .find('option:first-child').prop('selected', true)
                .end().trigger('chosen:updated');
			$('#select_form')
                .find('option:first-child').prop('selected', true)
                .end().trigger('chosen:updated');
        }
		$(document).ready(function () {
            jQuery(window).on('resize', function () {
				$("#select_form_school_chosen").attr('style', 'width: 100%');
				$("#select_form_class_chosen").attr('style', 'width: 100%');
				$("#select_form_chosen").attr('style', 'width: 100%');
            });
			var selected_school = `{{query.selected_school}}`
			var selected_class = `{{query.selected_class}}`
			if (selected_school){
				let urlClasses = $('#myForm').data('urlclasses')
				$.ajax({
					url: urlClasses,
					data: {
						id: selected_school
					},
					success: function (response) {
						$('#select_form_class').html(response);
						if (selected_class){
							$('#select_form_class').val(selected_class);
						}
						$('#select_form_class').trigger("chosen:updated");
					}
				})
			}
		})
		$(document).ready(function () {
			$('#select_form_school').on('change', function () {
				let urlClasses = $('#myForm').data('urlclasses')
				var selectValor = $(this).val();
				$.ajax({
					url: urlClasses,
					data: {
						id: selectValor
					},
					success: function (response) {
						$('#select_form_class').html(response);
						$('#select_form_class').trigger("chosen:updated");
					}
				})
				if (selectValor == '') {
					document.getElementById('selected_school').value = '0'
				}
				else {
					document.getElementById('selected_school').value = selectValor
				}
			});
		});
		$(document).ready(function () {
			$('#select_form_class').on('change', function () {
				var selectValor = $(this).val();
				if (selectValor == '') {
					document.getElementById('selected_class').value = '0'
				}
				else {
					document.getElementById('selected_class').value = selectValor
				}
			});
		});
		$(document).ready(function () {
			$('#select_form').on('change', function () {
				setGenPasswordToFields(['id_{{user_form.password1.name}}', 'id_{{user_form.password2.name}}']);
				var selectValor = $(this).val();
				if (selectValor == '') {
					document.getElementById('type_of_user').value = ''
				}
				else {
					document.getElementById('type_of_user').value = selectValor
				}
			});
		});
		$(document).ready(function () {
			$('#headstable').DataTable({
				aLengthMenu: [
					[10, 25, 50, 100, -1],
					[10, 25, 50, 100, "All"]
				],
				iDisplayLength: -1,
			});
			$(window).on('resize', function () {
				$('#headstable').DataTable();
			});
		});
		function changeYesLink(url) {
			document.getElementById("link_to_delete").href = url;
		};
	</script>
	<div id="delete-assinante-modal" class="modal fade" role="dialog">
		<div class="modal-dialog">

			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">x</span>
					</button>
				</div>
				<div class="modal-body">
					<p>Você tem certeza que deseja deletar este assinante? Essa operação não pode ser desfeita!</p>
				</div>
				<div class="modal-footer">
					<a id="link_to_delete" class="btn btn-danger btn-block" href="">Sim</a>
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
				</div>
			</div>

		</div>
	</div>

	{% endblock %}