classrooms/block/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views

router = routers.DefaultRouter()
router.register(r'chains', views.ChainViewSet)

urlpatterns = [
	url('', include(router.urls)),
    url(r'^blocks/(?P<chain_name>[A-Za-z0-9-]+)/latest$', views.LatestBlockApiView.as_view(), name='latest-block'),
    url(r'^blocks/(?P<chain_name>[A-Za-z0-9-]+)/mine-block$', views.BlockCreateView.as_view(), name='mine-block'),
    url(r'^blocks/(?P<hash>[A-Za-z0-9-]+)$', views.BlockApiView.as_view(), name='get'),
    url(r'^chains/(?P<name>[A-Za-z0-9-]+)$', views.ChainApiView.as_view(), name='chain'),
    url(r'^peers/$', views.PeerApiView.as_view(), name='peers'),
    url(r'^peers/add$', views.PeerApiView.as_view(), name='add-peer'),
    url(r'^transaction/$', views.TransactionsList.as_view(), name='transaction'),
]

classrooms/classrooms/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from classrooms import settings
from school.views import seeallschoolsbyquery
from django.views.static import serve 

urlpatterns = [
    path('datawizard/', include('data_wizard.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin_url/', admin.site.urls),
    url(r'^$', seeallschoolsbyquery),
    url('chain/', include('block.urls')),
    url('contracts/', include('contract.urls')),
    url('schools/', include('school.urls')),
    url('users/', include('school_users.urls')),
]
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

handler404 = 'school_users.views.handler404'
handler500 = 'school_users.views.handler500'

classrooms/contract/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views
from classrooms import settings

router = routers.DefaultRouter()
router.register(r'contracts', views.ContractsViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'contracts'
urlpatterns = [
    url('', include(router.urls)),
    path('mark_slm_purchased/<int:contract_id>', views.mark_slm_purchased, name="mark_slm_purchased"),
    url('createacontract/', views.createacontract, name="createacontract"),
    url('createacontract_rest/', views.createacontract_rest, name="createacontract_rest"),
    path('seecontractdetails/<int:contract_id>', views.seecontractdetails, name="seecontractdetails"),
    path('select_director_to_contract/<int:contract_id>', views.select_director_to_contract, name="select_director_to_contract"),
    url('all/', views.seecontractsbyquery, name="seemycontracts"),
    url('all_rest/', views.seemycontracts_rest, name="seemycontracts_rest"),
    path('set_signed/<int:contract_id>', views.set_signed, name='set_signed'),
    path('queue_set_signed/<int:contract_id>', views.queue_set_signed, name='queue_set_signed'),
    path('set_signed_rest/<int:contract_id>', views.set_signed_rest, name='set_signed_rest'),
    path('updatecontract/<int:contract_id>', views.updatecontract, name='updatecontract'),
    path('delete_contract/<int:contract_id>', views.delete_contract, name='delete_contract'),
    path('redirect_to_slm_link/<int:contract_id>', views.redirect_to_slm_link, name='redirect_to_slm_link'),
    path('seefinancialdetails/', views.seefinancialdetails, name='seefinancialdetails'),
    url('select_student_to_contract/', views.select_student_to_contract, name='select_student_to_contract'),
    path('select_student_to_contract_update/<int:contract_id>', views.select_student_to_contract_update, name='select_student_to_contract_update'),
    path(r'serve_protected/{}<path>/<int:contract_id>/<type_of_document>'.format(settings.MEDIA_URL[1:]), views.protected_serve, {'document_root': settings.MEDIA_ROOT}, name='serve_protected'),
    path('set_contract_paid/<int:contract_id>', views.set_contract_paid, name='set_contract_paid'),
    path('directors/ajax', views.directors_choices_ajax, name='directors_choices_ajax'),
    path('receive_maple_result/', views.receive_maple_result, name='receive_maple_result'),
    path('authenticated/', views.authenticated_google, name='authenticated'),
    path('upload_contract_file_to_drive/<int:contract_id>/<type_of_file>', views.upload_contract_file_to_drive, name='upload_contract_file_to_drive'),
    path('extend_expire_date/<int:contract_id>', views.extend_expire_date, name='extend_expire_date'),
    path('edit_dates/<int:contract_id>', views.edit_dates, name='edit_dates'),
]

classrooms/school/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views

router = routers.DefaultRouter()
router.register(r'schools', views.SchoolsViewSet)
router.register(r'schools_minimal', views.SchoolsViewSetMinimal)


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'school'
urlpatterns = [
    url('', include(router.urls)),
    url('import_xml/', views.import_xml, name='import_xml'),
    url('import_sponte/', views.import_sponte, name='import_sponte'),
    url('seeallschoolsbyquery/', views.seeallschoolsbyquery, name='seeallschoolsbyquery'),
    url('seeallclassesbyquery/', views.seeallclassesbyquery, name='seeallclassesbyquery'),
    path('seeclassbyid/<int:class_id>', views.seeclassbyid, name="seeclassbyid"),
    path('blockchain/<int:chain_id>', views.seechainbyid, name="seechainbyid"),
    url('add_school/', views.create_school, name="add_school"),
    url('seeallschools/', views.seeallschools, name="seeallschools"),
    url('select_school/', views.select_school, name="select_school"),
    path('seeschooldetails/<int:school_id>', views.seeschooldetails, name="seeschooldetails"),
    url('seeallschools_rest/', views.seeallschools_rest),
    path('update_school/<int:school_id>', views.update_school, name='update_school'),
    path('update_school_rest/<int:school_id>', views.update_school_rest, name='update_school_rest'),
    path('delete_school/<int:school_id>', views.delete_school, name='delete_school'),
    path('delete_school_rest/<int:school_id>', views.delete_school_rest, name='delete_school_rest'),
    path('<int:school_id>/add_class', views.add_class, name='add_class'),
    path('<int:school_id>/add_another_class', views.add_another_class, name='add_another_class'),
    path('<int:school_id>/add_another_class/add_students_for_multiple_classes', views.add_students_for_multiple_classes, name='add_students_for_multiple_classes'),
    path('<int:school_id>/add_another_class/select_class_to_add_students', views.select_class_to_add_students, name='select_class_to_add_students'),
    path('<int:school_id>/add_another_class/<int:class_id>/add_multiple_students', views.add_multple_students_for_class_and_school, name='add_multple_students_for_class_and_school'),
    path('<int:school_id>/add_first_witness', views.add_first_witness, name='add_first_witness'),
    path('<int:school_id>/add_second_witness', views.add_second_witness, name='add_second_witness'),
    path('<int:school_id>/add_witness/<type_of_user>', views.add_witness, name='add_witness'),
    path('<int:school_id>/set_witnesses', views.set_witnesses, name='set_witnesses'),
    path('<int:school_id>/add_class/<int:class_id>/add_student', views.add_student_to_class_and_school, name='add_student_to_class_and_school'),
    path('<int:school_id>/add_class/<int:class_id>/add_multiple_students', views.add_students_to_class_and_school, name='add_students_to_class_and_school'),
    path('<int:school_id>/add_class/<int:class_id>/add_student/<int:student_id>/add_first_parent_to_student', views.add_first_parent_to_student, name='add_first_parent_to_student'),
    path('<int:school_id>/add_class/<int:class_id>/add_student/<int:student_id>/add_second_parent_to_student', views.add_second_parent_to_student, name='add_second_parent_to_student'),
    path('add_students_to_school/<int:school_id>', views.add_students_to_school, name='add_students_to_school'),
    path('add_teachers_to_school/<int:school_id>', views.add_teachers_to_school, name='add_teachers_to_school'),
    path('add_teachers_to_class/<int:class_id>', views.add_teachers_to_class, name='add_teacher_to_class'),
    path('add_students_to_class/<int:class_id>', views.add_students_to_class, name='add_student_to_class'),
    path('add_class_rest/<int:school_id>', views.add_class_rest, name='add_class_rest'),
    path('update_class/<int:class_id>', views.update_class, name='update_class'),
    path('verifyvalidchain/<int:class_id>', views.verifyvalidchain, name='verifyvalidchain'),
    path('delete_class/<int:class_id>', views.delete_class, name='delete_class'),
    url('create_block/', views.create_block, name='create_block'),
    path('<int:school_id>/pull_students', views.pull_students, name='pull_students'),
    path('<int:school_id>/remove_non_active', views.remove_non_active_students, name='remove_non_active'),

]

classrooms/school_users/urls.py
from django.conf.urls import url
from rest_framework import routers
from django.urls import include, path, re_path
from . import views
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from django.contrib.auth.views import PasswordResetView

# router = routers.DefaultRouter()
# router.register(r'schools', views.SchoolsViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'users'
urlpatterns = [
    # url('', include(router.urls)),
    url('create_user/', views.create_user, name="create_user"),
    url('all_administration/', views.seeusersbyquery_administration, name="all_administration"),
    url('all_signes/', views.seeusersbyquery_signes, name="all_signes"),
    path('all_by_school/<int:school_id>', views.seeallusers_by_school, name='seeallusers_by_school'),
    url('all_rest/', views.seeallusers_rest),
    path('delete_user/<int:user_id>/<type_of_user>', views.delete_user, name='delete_user'),
    path('set_parents/<int:student_id>/', views.set_parents, name='set_parents'),
    path('add_parent/<int:student_id>/<type_of_user>', views.add_parent, name='add_parent'),
    path('select_parent/<int:student_id>/<type_of_user>', views.select_parent, name='select_parent'),
    path('confirm_parent/<int:student_id>/<int:parent_id>/<type_of_user>', views.confirm_parent, name='confirm_parent'),
    path('add_first_parent/<int:student_id>', views.add_first_parent, name='add_first_parent'),
    path('add_second_parent/<int:student_id>', views.add_second_parent, name='add_second_parent'),
    path('classes/ajax', views.classes_choices_ajax, name='classes_choices_ajax'),
    path('students/ajax', views.students_choices_ajax, name='students_choices_ajax'),
    url('add_student/', views.add_student, name='add_student'),
    url('login/', views.do_login, name='login'),
    path('login_from_other_system/<username>', views.login_from_other_system, name='login_from_other_system'),
    url('logout', views.do_logout, name='logout'),
    url('api/login', obtain_jwt_token, name='login_rest'),
    url('api/refresh_token', refresh_jwt_token, name='refresh_token'),
    url('current_user/', views.current_user, name='current_user'),
    path('create_head_to_school/<int:school_id>', views.create_head_to_school, name='create_head_to_school'),
    path('create_supervisor_to_school/<int:school_id>', views.create_supervisor_to_school, name='create_supervisor_to_school'),
    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.reset_password, name='reset_password'),
    url('generate_password', views.generate_password, name='generate_password'),
    url('profile', views.profile, name='profile'),
    url('update_perfil', views.update_profile, name='update_perfil'),
    path('do_u_need_parents/<int:student_id>/<int:school_id>/<int:class_id>', views.do_u_need_parents, name='do_u_need_parents'),
    path('seesonsofparent/<int:parent_id>', views.seesonsofparent, name='seesonsofparent'),
    path('reset_password_send_email/<int:user_id>/<type_of_user>', views.reset_password_send_email, name='reset_password_send_email'),
    path('change_email/<user_id>', views.change_email, name='change_email'),
    path('room/<str:room_name>/', views.room, name='room'),
    url('forgot_password', views.forgot_password, name='forgot_password'),
]

classrooms/classrooms/templates/base.html
<!DOCTYPE html>
<html>

<head>
  {% load static %}
  <title>{% block title %} Schools Creation {% endblock %}</title>

  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
    name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
  <!-- CSS Files -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
  <link rel="stylesheet" href="{% static 'css/light-bootstrap-dashboard.css' %}" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <!--<link href="../assets/css/demo.css" rel="stylesheet" /> -->
  <script src="{% static 'js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>


  <link rel="stylesheet" type="text/css" href="{% static 'datatables/datatables.min.css' %}" />
  <script type="text/javascript" src="{% static 'datatables/datatables.min.js' %}"></script>




<!-- Generate password -->
<script src="{% static 'js/gen_password.js' %}"></script>
<script>

  function setGenPasswordToFields(fieldsIds) {
    $(document).ready(function() {
      var password = genPassword();

      if (fieldsIds.length) {
        for (var i = 0; i < fieldsIds.length; i++) {
          var passwordElement = document.getElementById(fieldsIds[i]);
          if (passwordElement) {
            passwordElement.value = password;
          }
        }
      }
    });
  }

</script>

  <script src="{% static 'js/bootstrap-3.1.1.min.js' %}"></script>




  <link rel="stylesheet" href="{% static 'css/forms.css' %}" />
  <link rel="stylesheet" href="{% static 'css/all.css' %}" />
  <script src="{% static 'js/chosen.jquery.min.js' %}" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'js/chosen.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>

<body>
  <div class="wrapper">
    {% include 'top-navbar.html' %}
    <div class="main-panel">
      {% comment %} {% include 'panel.html' %} {% endcomment %}
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %}
        class="{{ message.tags }} alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}"
        {% endif %} role="alert"><span style="align-content: center;">{{ message }}</span><button type="button"
          class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
      {% endfor %}
      {% endif %}
      {% if form.errors %}
      <div id="form-error">
        {% for field in form %}
        {% if field.errors %}
        <div class="alert alert-danger" role="alert"><span
            style="align-content: center;">{{ field.errors|striptags }}</span><button type="button" class="close"
            data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
        {% endif %}
        {% endfor %}
      </div>
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>
    {% include 'footer.html' %}
  </div>

<!-- Start of agendatellme Zendesk Widget script -->
<script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=7f525ea7-1261-4c55-833a-5dc3de533cb7"> </script>
<!-- End of agendatellme Zendesk Widget script -->
</body>

</html>
<!--   Core JS Files   -->

<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>

<!--  Chartist Plugin  -->
<script src="{% static 'js/plugins/chartist.min.js' %}"></script>

<script src="{% static 'js/plugins/jquery.sharrre.js' %}"></script>

<!--  Notifications Plugin    -->
<script src="{% static 'js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="{% static 'js/light-bootstrap-dashboard.js' %}"></script>

<script src="{% static 'js/demo.js'%}"></script>


<script type="text/javascript">
  $(".chosen-select").chosen({ no_results_text: "Oops, nothing found!" });
  function downloadCSV(csv, filename) {
    var csvFile;
    var downloadLink;

    // CSV file
    csvFile = new Blob([csv], {type: "text/csv",encoding:'windows-1252'});

    // Download link
    downloadLink = document.createElement("a");

    // File name
    downloadLink.download = filename;

    // Create a link to the file
    downloadLink.href = window.URL.createObjectURL(csvFile);

    // Hide download link
    downloadLink.style.display = "none";

    // Add the link to DOM
    document.body.appendChild(downloadLink);

    // Click download link
    downloadLink.click();
  }
  function exportTableToCSV(filename) {
    var csv = [];
    var rows = document.querySelectorAll("table tr");
    
    for (var i = 0; i < rows.length; i++) {
        var row = [], cols = rows[i].querySelectorAll("td, th");
        
        for (var j = 0; j < cols.length-1; j++) 
            row.push(cols[j].innerText.replace(/(\r\n|\n|\r)/gm, ' ').replace(/(\s\s)/gm, ' ').replace(/"/g, '""'));
        
        csv.push(row.join(","));        
    }

    // Download CSV file
    downloadCSV(csv.join("\n"), filename);
}
</script>

classrooms/classrooms/templates/footer.html
<footer class="footer">
    <div class="container-fluid">
        <nav>
            <ul class="footer-menu">

            </ul>
            <p class="copyright text-center">
                ©
                <script>
                    document.write(new Date().getFullYear())
                </script>
                TellMe School
            </p>
        </nav>
    </div>
</footer>

classrooms/classrooms/templates/navbar.html
{% load static %}
    <div class="sidebar" data-image="">
        <!--
    Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

    Tip 2: you can also add an image using data-image tag
-->
        <div class="sidebar-wrapper">
            <div class="logo">

              <a href="" class="simple-text">
                  <img src="{% static 'img/logotell.png'%}" alt="">
              </a>

            </div>

            <ul class="nav top-nav">

              <li class="nav-item">
                <div class="nav-link">

                  <div class="distribute-elements">
                    <a style="color:#FFFFFF;" href="{% url 'contracts:seemycontracts'%}">
                      <i class="fas fa-file-contract"></i>
                      <p>Contrato(s) </p>
                    </a>
  
                    {% if request.user.is_superuser or is_supervisor %}
                      <p class="box-rounded plus-float-right">
                        <a class="fas fa-plus centralize-margin font-size-plus" href="{% url 'contracts:select_student_to_contract' %}"></a>
                      </p>
                    {% endif %}
                  </div>

                </div>
              </li>

              {% if request.user.is_superuser or is_supervisor %}

                <li class="nav-item">
                  <div class="nav-link">

                    <div class="distribute-elements">
                      <a style="color:#FFFFFF;" href="/">  
                        <i class="fas fa-graduation-cap"></i>
                        <p>Escola(s) </p>
                      </a>
  
                      {% if request.user.is_superuser %}
                        <p class="box-rounded plus-float-right">
                          <a class="fas fa-plus centralize-margin font-size-plus" href="{% url 'school:add_school' %}"></a>
                        </p>
                      {% endif %}
                    </div>

                  </div>
                </li>
              {% endif %}


              {% if request.user.is_superuser or is_supervisor %}

                <li class="nav-item">
                  <div class="nav-link">

                    <div class="distribute-elements">
                      <a style="color:#FFFFFF;" href="{% url 'users:seeallusers' %}">
                        <i class="fas fa-user"></i>
                        <p>Usuário(s) </p>
                      </a>
  
                      <p class="box-rounded plus-float-right">
                        <a class="fas fa-plus centralize-margin font-size-plus" href="{% url 'users:create_user' %}"></a>
                      </p>
                    </div>

                  </div>
                </li>
              {% endif %}

            </ul>
        </div>
    </div>

classrooms/classrooms/templates/panel.html
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">

    <div class="collapse navbar-collapse justify-content-end" id="navigation">

      <ul class="nav navbar-nav mr-auto">

        <li class="nav-item">
          <button class="btn btn-info btn-sm pull-left btn-fill" type="button" onclick="goBack()" style="background-color: #213f99; border-color: #213f99">Página anterior</button>
        </li>

      </ul>

      <ul class="navbar-nav ml-auto">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user" style="margin-right: 10px"></i>{{request.user.username}}</a>
          <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
            <a class="dropdown-item" href="{% url 'users:logout' %}">Sair</a>
          </div>
        </li>

      </ul>

    </div>
  </div>
</nav>

<script>
function goBack() {
  window.history.back();
}
</script>

classrooms/classrooms/templates/top-navbar.html
{% load static %}
<div class="topbar" data-image="">
    
    <div class="topbar-wrapper">
        <div class="logo">

            <a href="/" class="simple-text">
                <img src="{% static 'img/Matrícula (002).png'%}" alt="" width="75px" height="75px">
            </a>

        </div>

        <li style="float: right;" class="nav-item item-centering list-item-size">
          <button class="btn btn-info btn-sm pull-left btn-fill" type="button" onclick="goBack()" style="background-color: #213f99; border-color: #213f99;  margin: 0 auto;">Página anterior</button>
        </li>

        <ul class="nav top-nav top-bar-icons">

            {% if request.user.is_superuser or is_supervisor %}

            <li class="nav-item item-centering list-item-size list-item-hover-background">
                <p class="text-top-bar-nav">
                    <i class="fas fa-graduation-cap"></i>
                    <a style="color:#FFFFFF;" href="/">
                        Escolas 
                    </a>
                </p>

                {% if request.user.is_superuser %}
                <a class="box-rounded flex-div coloring-link" href="{% url 'school:add_school' %}">
                    <p class="fas fa-plus centralize-margin font-size-plus"></p>
                </a>
                {% endif %}
            </li>
            {% endif %}

            {% if request.user.is_superuser or is_supervisor %}

            <li class="nav-item item-centering list-item-size list-item-hover-background">
                <p class="text-top-bar-nav">
                    <i class="fas fa-graduation-cap"></i>
                    <a style="color:#FFFFFF;" href="{% url 'school:seeallclassesbyquery' %}">
                        Turmas 
                    </a>
                </p>

                <a class="box-rounded flex-div coloring-link" href="{% url 'school:select_school' %}">
                    <p class="fas fa-plus centralize-margin font-size-plus"></p>
                </a>
            </li>
            {% endif %}


            {% if request.user.is_superuser or is_supervisor %}

            <li class="nav-item item-centering list-item-size list-item-hover-background">
                <p class="text-top-bar-nav">
                    <i class="fas fa-user"></i>
                    <a style="color:#FFFFFF;" href="{% url 'users:all_administration' %}">
                        Usuários
                    </a>
                </p>

                {% if request.user.is_superuser %}
                    <a class="box-rounded flex-div coloring-link" href="{% url 'users:create_user' %}">
                        <p class="fas fa-plus centralize-margin font-size-plus"></p>
                    </a>
                {% endif %}
            </li>

            <li class="nav-item item-centering list-item-size list-item-hover-background">
                <p class="text-top-bar-nav">
                    <i class="fas fa-user"></i>
                    <a style="color:#FFFFFF;" href="{% url 'users:all_signes' %}">
                        Assinantes 
                    </a>
                </p>


                <a class="box-rounded flex-div coloring-link" href="{% url 'users:create_user' %}">
                    <p class="fas fa-plus centralize-margin font-size-plus"></p>
                </a>
            </li>
            {% endif %}

            <li class="nav-item item-centering list-item-size list-item-hover-background">
                <p class="text-top-bar-nav">
                    <i class="fas fa-file-contract"></i>
                    <a style="color:#FFFFFF;" href="{% url 'contracts:seemycontracts'%}">
                        Contratos 
                    </a>                            
                </p>

                {% if request.user.is_superuser or is_supervisor %}
                <a href="{% url 'contracts:select_student_to_contract' %}" class="box-rounded flex-div coloring-link">
                    <p class="fas fa-plus centralize-margin font-size-plus"></p>
                </a>
                {% endif %}
            </li>



        </ul>

        <li style="float: right" class="nav-item item-centering list-item-size dropdown">
            <a href="#" style="color: white" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user" style="margin-right: 10px"></i>
                {{request.user.username}}
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                {% if is_client %}
                    <a class="dropdown-item" href="{% url 'users:profile' %}">Perfil</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'contracts:authenticated' %}">Autenticar com Google</a>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Sair</a>
            </div>
        </li>

    </div>
</div>

<script>
function goBack() {
  window.history.back();
}
</script>